In [1]:
import sys
sys.path.append('../../dmrt/')

In [2]:
import diffTools
import numpy as np

In [3]:
difft = diffTools.DiffTools()

In [4]:
length=10000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,upts,distro,tpdistro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)

[[ 0.00000000e+00  1.68488337e+00]
 [ 1.00000000e-04 -1.31000917e-01]
 [ 2.00000000e-04 -1.29244116e-01]
 ...
 [ 9.99999700e+02 -7.23642406e-01]
 [ 9.99999800e+02 -9.54941452e-01]
 [ 9.99999900e+02 -8.13301279e-01]]
6 5 5 5 5
[-2. -1.  0.  1.  2.] [[        nan         nan         nan         nan         nan]
 [        nan  0.                 nan -0.00071363         nan]
 [        nan         nan  0.                 nan         nan]
 [        nan  0.00071363         nan  0.                 nan]
 [        nan         nan         nan         nan         nan]] [[       0        0        0        0        0]
 [       0  7505136        0  7501776        0]
 [       0        0 10001032        0        0]
 [       0  7501776        0  7498420        0]
 [       0        0        0        0        0]] [[      0       0       0       0       0]
 [      0 3752568       0 1250284       0]
 [      0       0 5000516       0       0]
 [      0 1250285       0 3749210       0]
 [      0       0      

../../dmrt/diffTools.py:39: RuntimeWarning: invalid value encountered in true_divide
  tms = tms/cts


In [5]:
del difft

In [6]:
del inp, dists,tms,cts,upts,distro