In [3]:
import sys
sys.path.append('../../dmrt/')

In [4]:
import diffTools
import numpy as np

import gc

In [5]:
# create and clean up numpy array

length=50000000
inp = np.random.rand(length,2)*4-2

In [6]:
del inp

In [17]:
difft = diffTools.DiffTools()

In [18]:
length=10000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,errs,upts,distro,tpdistro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)
print("finish")

[[ 0.00000000e+00 -1.53516127e+00]
 [ 1.00000000e-04  1.64973952e-02]
 [ 2.00000000e-04  1.58015087e+00]
 ...
 [ 9.99999700e+02 -5.41824553e-01]
 [ 9.99999800e+02 -1.94892846e+00]
 [ 9.99999900e+02  9.48055041e-01]]
[-2. -1.  0.  1.  2.] [[       nan        nan        nan        nan        nan]
 [       nan  0.               nan -0.0007143        nan]
 [       nan        nan  0.               nan        nan]
 [       nan  0.0007143        nan  0.               nan]
 [       nan        nan        nan        nan        nan]] [[      0       0       0       0       0]
 [      0 7501384       0 7496330       0]
 [      0       0 9995340       0       0]
 [      0 7496330       0 7491280       0]
 [      0       0       0       0       0]] [[      0       0       0       0       0]
 [      0 3750692       0 1248967       0]
 [      0       0 4997670       0       0]
 [      0 1248968       0 3745640       0]
 [      0       0       0       0       0]]
finish


In [19]:
print("test")
print(sys.getrefcount(inp))

test
2


In [20]:
del difft

In [21]:
del inp,dists,tms,cts,errs,upts,distro,tpdistro
#gc.collect()

In [17]:
from guppy import hpy
h = hpy()
print(h.heap())

Partition of a set of 514876 objects. Total size = 66146290 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 149890  29 21334135  32  21334135  32 str
     1 123933  24  9119392  14  30453527  46 tuple
     2  34047   7  6050786   9  36504313  55 types.CodeType
     3  67084  13  5472918   8  41977231  63 bytes
     4  31771   6  4320856   7  46298087  70 function
     5   3661   1  3646112   6  49944199  76 type
     6  10155   2  3470512   5  53414711  81 dict (no owner)
     7   1487   0  2310224   3  55724935  84 dict of module
     8   3661   1  1939752   3  57664687  87 dict of type
     9   6930   1   831504   1  58496191  88 list
<1278 more rows. Type e.g. '_.more' to view.>
