In [1]:
import sys
sys.path.append('../../dmrt/')
import gc

In [2]:
import diffTools
import numpy as np

import gc

In [3]:
# create and clean up numpy array

length=50000000
inp = np.random.rand(length,2)*4-2

In [4]:
del inp

In [5]:
difft = diffTools.DiffTools()

In [6]:
length=10000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,errs,upts,distro,tpdistro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)
print("finish")

[[ 0.00000000e+00  1.35774324e+00]
 [ 1.00000000e-04 -1.43908583e+00]
 [ 2.00000000e-04  1.87889965e+00]
 ...
 [ 9.99999700e+02  7.78024555e-01]
 [ 9.99999800e+02 -2.54153143e-01]
 [ 9.99999900e+02 -4.81374323e-01]]
[-2. -1.  0.  1.  2.] [[        nan         nan         nan         nan         nan]
 [        nan  0.                 nan -0.00071355         nan]
 [        nan         nan  0.                 nan         nan]
 [        nan  0.00071355         nan  0.                 nan]
 [        nan         nan         nan         nan         nan]] [[      0       0       0       0       0]
 [      0 7495066       0 7498509       0]
 [      0       0 9995696       0       0]
 [      0 7498509       0 7501956       0]
 [      0       0       0       0       0]] [[      0       0       0       0       0]
 [      0 3747533       0 1249747       0]
 [      0       0 4997848       0       0]
 [      0 1249747       0 3750978       0]
 [      0       0       0       0       0]]
finish


../../dmrt/diffTools.py:41: RuntimeWarning: invalid value encountered in true_divide
  tms = tms/cts
../../dmrt/diffTools.py:42: RuntimeWarning: invalid value encountered in true_divide
  errs = np.sqrt(wars)/cts


In [ ]:
print("test")
print(sys.getrefcount(tpdistro))

In [ ]:
from guppy import hpy
h = hpy()
print(h.heap())

In [9]:
del difft

In [10]:
del inp,dists,tms,cts,errs,upts,distro,tpdistro
gc.collect()

5624

In [11]:
from guppy import hpy
h = hpy()
print(h.heap())

Partition of a set of 486326 objects. Total size = 58971675 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 149262  31 18799355  32  18799355  32 str
     1 128922  27 10080520  17  28879875  49 tuple
     2  57362  12  4708103   8  33587978  57 bytes
     3  29075   6  4209936   7  37797914  64 types.CodeType
     4  26525   5  3607400   6  41405314  70 function
     5   3069   1  2998848   5  44404162  75 type
     6   5660   1  2325352   4  46729514  79 dict (no owner)
     7   1235   0  2022392   3  48751906  83 dict of module
     8   3069   1  1686408   3  50438314  86 dict of type
     9   2866   1  1054688   2  51493002  87 dict of matplotlib.font_manager.FontEntry
<1151 more rows. Type e.g. '_.more' to view.>
