In [1]:
import sys
sys.path.append('../../dmrt/')

In [2]:
import diffTools
import numpy as np

In [3]:
difft = diffTools.DiffTools()

In [4]:
length=10000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,upts,distro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)

[[ 0.00000000e+00 -1.17138070e+00]
 [ 1.00000000e-04  8.72198720e-01]
 [ 2.00000000e-04  1.47554767e+00]
 ...
 [ 9.99999700e+02 -1.92378199e-01]
 [ 9.99999800e+02  1.71055098e+00]
 [ 9.99999900e+02  1.34265627e+00]]
[-2. -1.  0.  1.  2.] [[        nan         nan         nan         nan         nan]
 [        nan  0.                 nan -0.00071342         nan]
 [        nan         nan  0.                 nan         nan]
 [        nan  0.00071342         nan  0.                 nan]
 [        nan         nan         nan         nan         nan]] [[       0        0        0        0        0]
 [       0  7500568        0  7501554        0]
 [       0        0 10000888        0        0]
 [       0  7501554        0  7502542        0]
 [       0        0        0        0        0]] [[      0       0       0       0       0]
 [      0 3750284       0 1250270       0]
 [      0       0 5000444       0       0]
 [      0 1250270       0 3751271       0]
 [      0       0       0       0

../../dmrt/diffTools.py:39: RuntimeWarning: invalid value encountered in true_divide
  tms = tms/cts


In [5]:
del difft

In [6]:
del inp, dists,tms,cts,upts,distro