In [1]:
import sys
sys.path.append('../../dmrt/')

In [2]:
import diffTools
import numpy as np

In [3]:
difft = diffTools.DiffTools()

In [4]:
length=10000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,upts,distro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)

[[ 0.00000000e+00 -1.73605006e+00]
 [ 1.00000000e-04 -1.54814925e+00]
 [ 2.00000000e-04 -4.72722405e-01]
 ...
 [ 9.99999700e+02  1.57213192e+00]
 [ 9.99999800e+02  1.11421756e+00]
 [ 9.99999900e+02 -1.22750154e+00]]
[-2. -1.  0.  1.  2.] [[        nan         nan         nan         nan         nan]
 [        nan  0.                 nan -0.00071497         nan]
 [        nan         nan  0.                 nan         nan]
 [        nan  0.00071497         nan  0.                 nan]
 [        nan         nan         nan         nan         nan]] [[      0       0       0       0       0]
 [      0 3745708       0 3746857       0]
 [      0       0 4994744       0       0]
 [      0 3746857       0 3748008       0]
 [      0       0       0       0       0]] [[      0       0       0       0       0]
 [      0 1872854       0  623950       0]
 [      0       0 2497372       0       0]
 [      0  623950       0 1874004       0]
 [      0       0       0       0       0]]


../../dmrt/diffTools.py:38: RuntimeWarning: invalid value encountered in true_divide
  tms = tms/cts*2 #make them RTT again


In [6]:
del difft

NameError: name 'difft' is not defined

In [7]:
del inp, dists,tms,cts,upts,distro