In [1]:
import sys
sys.path.append('../../dmrt/')

In [2]:
import diffTools
import numpy as np

In [3]:
difft = diffTools.DiffTools()

In [4]:
length=100000000
inp = np.random.rand(length,2)*4-2
inp[:,0] = np.arange(length)*0.0001
print(inp)
dists,tms,cts,upts,distro = difft.compute(inp, mode='rtcrossdist',radii=[-2,-1,0,1,2],verb=True)
print(dists,tms,cts,upts)

[[ 0.00000000e+00  3.36388952e-01]
 [ 1.00000000e-04 -5.15153540e-01]
 [ 2.00000000e-04 -1.49365639e+00]
 ...
 [ 9.99999970e+03 -1.87335520e+00]
 [ 9.99999980e+03  3.09176132e-01]
 [ 9.99999990e+03 -1.46732726e+00]]
[-2. -1.  0.  1.  2.] [[        nan         nan         nan         nan         nan]
 [        nan  0.                 nan -0.00071395         nan]
 [        nan         nan  0.                 nan         nan]
 [        nan  0.00071395         nan  0.                 nan]
 [        nan         nan         nan         nan         nan]] [[       0        0        0        0        0]
 [       0 37499182        0 37491964        0]
 [       0        0 50005448        0        0]
 [       0 37491964        0 37484752        0]
 [       0        0        0        0        0]] [[       0        0        0        0        0]
 [       0 18749591        0  6247708        0]
 [       0        0 25002724        0        0]
 [       0  6247708        0 18742376        0]
 [       0   

../../dmrt/diffTools.py:38: RuntimeWarning: invalid value encountered in true_divide
  tms = tms/cts*2 #make them RTT again


In [ ]:
del difft

In [ ]:
del inp, dists,tms,cts,upts,distro